-- Restrict admin access to an explicit allow-list of users.
--
-- Previously every "authenticated" user had full write access, so anyone who
-- signed up through Supabase Auth could edit or delete all data.
--
-- Run this once in the Supabase SQL Editor, then add your admin account:
--   INSERT INTO public.admins (user_id)
--   SELECT id FROM auth.users WHERE email = 'you@example.com';

CREATE TABLE IF NOT EXISTS public.admins (
    user_id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
-- No policies on admins: it can only be changed from the SQL Editor / service role.

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (SELECT 1 FROM public.admins WHERE user_id = auth.uid());
$$;

REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin() TO anon, authenticated;

-- Removal requests table used by the Admin page.
CREATE TABLE IF NOT EXISTS public.worker_removal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.worker_removal_requests ENABLE ROW LEVEL SECURITY;

-- Replace the old "any authenticated user" policies with admin-only ones.
DROP POLICY IF EXISTS "Allow admin all on rates" ON public.daily_rates;
DROP POLICY IF EXISTS "Allow admin all on notices" ON public.notices;
DROP POLICY IF EXISTS "Allow admin all on workers" ON public.skilled_workers;
DROP POLICY IF EXISTS "Allow admin all on scholarships" ON public.scholarships;
DROP POLICY IF EXISTS "Allow admin all on opportunities" ON public.opportunities;
DROP POLICY IF EXISTS "Allow admin all on exams" ON public.entrance_exams;
DROP POLICY IF EXISTS "Allow admin all on removal requests" ON public.worker_removal_requests;

CREATE POLICY "Allow admin all on rates" ON public.daily_rates FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Allow admin all on notices" ON public.notices FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Allow admin all on workers" ON public.skilled_workers FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Allow admin all on scholarships" ON public.scholarships FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Allow admin all on opportunities" ON public.opportunities FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Allow admin all on exams" ON public.entrance_exams FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Allow admin all on removal requests" ON public.worker_removal_requests FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
