-- Create entrance_exams table with RLS
CREATE TABLE IF NOT EXISTS public.entrance_exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_name_en TEXT NOT NULL,
    exam_name_as TEXT NOT NULL,
    conducting_body TEXT NOT NULL,
    category TEXT DEFAULT 'general',
    eligibility_en TEXT,
    eligibility_as TEXT,
    apply_link TEXT NOT NULL,
    deadline DATE NOT NULL,
    exam_date DATE,
    is_approved BOOLEAN DEFAULT FALSE,
    source_type TEXT DEFAULT 'automated_public_feed',
    tracked_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.entrance_exams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read on approved exams" ON public.entrance_exams;
DROP POLICY IF EXISTS "Allow tracker exam insert" ON public.entrance_exams;
DROP POLICY IF EXISTS "Allow admin all on exams" ON public.entrance_exams;

CREATE POLICY "Allow public read on approved exams" 
ON public.entrance_exams FOR SELECT 
USING (is_approved = true);

CREATE POLICY "Allow tracker exam insert" 
ON public.entrance_exams FOR INSERT 
WITH CHECK (is_approved = false);

CREATE POLICY "Allow admin all on exams" 
ON public.entrance_exams FOR ALL 
TO authenticated 
USING (true);
