-- Let visitors submit worker removal requests from the Skilled Workers section.
-- Requests appear in the Admin page's Removals tab; only admins can read or delete them
-- (policy "Allow admin all on removal requests" in admin_security.sql).
-- Run once in the Supabase SQL Editor, after admin_security.sql.

CREATE TABLE IF NOT EXISTS public.worker_removal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- In case the table was created earlier with different columns
ALTER TABLE public.worker_removal_requests ADD COLUMN IF NOT EXISTS worker_name TEXT;
ALTER TABLE public.worker_removal_requests ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE public.worker_removal_requests ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE public.worker_removal_requests ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.worker_removal_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public removal request insert" ON public.worker_removal_requests;
CREATE POLICY "Allow public removal request insert"
ON public.worker_removal_requests FOR INSERT
TO anon, authenticated
WITH CHECK (
    length(trim(worker_name)) BETWEEN 1 AND 100
    AND phone_number ~ '^[6-9][0-9]{9}$'
    AND (reason IS NULL OR length(reason) <= 500)
);

GRANT INSERT ON public.worker_removal_requests TO anon, authenticated;
