CREATE TABLE IF NOT EXISTS public.daily_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_key TEXT UNIQUE NOT NULL,
    title_en TEXT NOT NULL,
    title_as TEXT NOT NULL,
    rate_value TEXT NOT NULL,
    unit_en TEXT,
    unit_as TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_en TEXT NOT NULL,
    title_as TEXT NOT NULL,
    details_en TEXT,
    details_as TEXT,
    category TEXT DEFAULT 'general',
    file_url TEXT,
    is_pinned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.skilled_workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    skill_en TEXT NOT NULL,
    skill_as TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    chuburi_ward TEXT NOT NULL,
    experience_years INT DEFAULT 1,
    is_verified BOOLEAN DEFAULT FALSE,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.scholarships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_en TEXT NOT NULL,
    title_as TEXT NOT NULL,
    provider TEXT NOT NULL,
    eligibility_en TEXT,
    eligibility_as TEXT,
    benefit_amount TEXT,
    apply_link TEXT NOT NULL,
    deadline DATE NOT NULL,
    is_approved BOOLEAN DEFAULT FALSE,
    source_type TEXT DEFAULT 'automated_official_feed',
    tracked_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.opportunities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT DEFAULT 'job',
    title_en TEXT NOT NULL,
    title_as TEXT NOT NULL,
    eligibility_en TEXT,
    eligibility_as TEXT,
    official_link TEXT,
    deadline DATE,
    is_approved BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.daily_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skilled_workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scholarships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.opportunities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on rates" ON public.daily_rates FOR SELECT USING (true);
CREATE POLICY "Allow public read on notices" ON public.notices FOR SELECT USING (true);
CREATE POLICY "Allow public read on workers" ON public.skilled_workers FOR SELECT USING (is_verified = true);
CREATE POLICY "Allow public read on scholarships" ON public.scholarships FOR SELECT USING (is_approved = true);
CREATE POLICY "Allow public read on opportunities" ON public.opportunities FOR SELECT USING (is_approved = true);

CREATE POLICY "Allow public worker insert" ON public.skilled_workers FOR INSERT WITH CHECK (is_verified = false);
CREATE POLICY "Allow tracker scholarship insert" ON public.scholarships FOR INSERT WITH CHECK (is_approved = false);

CREATE POLICY "Allow admin all on rates" ON public.daily_rates FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow admin all on notices" ON public.notices FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow admin all on workers" ON public.skilled_workers FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow admin all on scholarships" ON public.scholarships FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow admin all on opportunities" ON public.opportunities FOR ALL TO authenticated USING (true);
